### ISSUE TITLE
Inputs are being rendered with default system font instead of Bahnschrift

### ISSUE THREAD

**Issue by joelalejandro** [WebConfTech/website-2019#24]
Expected:
![image](https://user-images.githubusercontent.com/118913/54579341-44e64180-49c0-11e9-89a7-d55c2ecee3ca.png)

Rendered:
![image](https://user-images.githubusercontent.com/118913/54579323-2bdd9080-49c0-11e9-8bdd-876343090e5e.png)

**Comment by asermax** [comment]
I think this one should be fixed.
